relativeURLs = true
baseURL = "/"
languageCode = "en"
title = "George's Blog"
theme = "hugo-ink"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
      identifier = "about me"
      name = "About Me"
      url = "about_me"
      weight = 2
  [[menu.main]]
      identifier = "back"
      name = "Back to my website"
      url = "https://ginger-ninja.uk"
      weight = 30
